name: example
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOMAIN: example.com
  USERNAME: sriva
  REPOSITORY_URL: https://github.com/sriva/my-repo.git
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  EC2_INSTANCE_IP: 34.222.124.185
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        environment: [dev, staging, production]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Connect to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_INSTANCE_IP }}
        username: Automated_Data_Lake # or whatever user you are using on the EC2 instance
        key: ${{ env.SSH_PRIVATE_KEY }}

    - name: Deploy
      env:
        DOMAIN: ${{ env.DOMAIN }}
        USERNAME: ${{ env.USERNAME }}
        REPOSITORY_URL: ${{ env.REPOSITORY_URL }}
        ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
        OS: ${{ matrix.os }}
        ENVIRONMENT: ${{ matrix.environment }}
      run: |
      
        
