name:ex
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        environment: [dev, staging, production]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Deploy to EC2 Instance
        uses: actions/checkout@v2
        env:
            DOMAIN: example.com
            REPOSITORY_URL: https://github.com/sriva/my-repo.git
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            OS: ${{ matrix.os }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            ENVIRONMENT: ${{ matrix.environment }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
