name: example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOMAIN: example.com
  USERNAME: sriva
  REPOSITORY_URL: https://github.com/sriva/my-repo.git
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        environment: [dev, staging, production]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Connect to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ env.SSH_PRIVATE_KEY }}
        port: 200

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Deploy code
      env:
        DOMAIN: ${{ env.DOMAIN }}
        USERNAME: ${{ env.USERNAME }}
        REPOSITORY_URL: ${{ env.REPOSITORY_URL }}
        ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
        OS: ${{ matrix.os }}
        ENVIRONMENT: ${{ matrix.environment }}
      run: |
        
