name: example
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOMAIN: example.com
  REPOSITORY_URL: https://github.com/sriva/my-repo.git
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOST_NAME: ${{ secrets.HOSTNAME }}
  USER_NAME: ${{ secrets.USERNAME }}

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        environment: [dev, staging, production]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2 instance
      env:
        DOMAIN: ${{ env.DOMAIN }}
        REPOSITORY_URL: ${{ env.REPOSITORY_URL }}
        ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
        OS: ${{ matrix.os }}
        ENVIRONMENT: ${{ matrix.environment }}
        USER_NAME: ${{ env.USER_NAME }}
        HOST_NAME: ${{ env.HOST_NAME }}
        SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
        
      run: |
         echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
         ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME}

